export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const POST_TEACHERS_SUCCESS = 'POST_TEACHERS_SUCCESS'
export const POST_MANY_TEACHERS_SUCCESS = 'POST_MANY_TEACHERS_SUCCESS'
export const UPDATE_TEACHERS_SUCCESS = 'UPDATE_TEACHERS_SUCCESS'
export const UPDATE_MANY_TEACHERS_SUCCESS = 'UPDATE_MANY_TEACHERS_SUCCESS'
export const DELETE_ONE_TEACHERS_SUCCESS = 'DELETE_ONE_TEACHERS_SUCCESS'
export const DELETE_MANY_TEACHERS_SUCCESS = 'DELETE_MANY_TEACHERS_SUCCESS'


export default {
  GET_TEACHERS_SUCCESS,
  POST_TEACHERS_SUCCESS,
  POST_MANY_TEACHERS_SUCCESS,
  UPDATE_TEACHERS_SUCCESS,
  UPDATE_MANY_TEACHERS_SUCCESS,
  DELETE_ONE_TEACHERS_SUCCESS,
  DELETE_MANY_TEACHERS_SUCCESS
};
