export const GET_TEACHERS_SUCCESS = "GET_TEACHERS_SUCCESS";
export const GET_CURRENT_SUCCESS = 'GET_CURRENT_SUCCESS'
export const POST_MANY_TEACHERS_SUCCESS = 'POST_MANY_TEACHERS_SUCCESS'
export const UPDATE_TEACHERS_SUCCESS = 'UPDATE_TEACHERS_SUCCESS'
export const UPDATE_MANY_TEACHERS_SUCCESS = 'UPDATE_MANY_TEACHERS_SUCCESS'
export const DELETE_ONE_TEACHERS_SUCCESS = 'DELETE_ONE_TEACHERS_SUCCESS'
export const DELETE_MANY_TEACHERS_SUCCESS = 'DELETE_MANY_TEACHERS_SUCCESS'
export const GET_COUNT_STUDENT = 'GET_COUNT_STUDENT'

export const GET_COUNT_CURRENT = 'GET_COUNT_CURRENT'
export const GET_SCHEDULES = 'GET_SCHEDULES'


export default {
  GET_TEACHERS_SUCCESS,
  GET_CURRENT_SUCCESS,
  POST_MANY_TEACHERS_SUCCESS,
  UPDATE_TEACHERS_SUCCESS,
  UPDATE_MANY_TEACHERS_SUCCESS,
  DELETE_ONE_TEACHERS_SUCCESS,
  DELETE_MANY_TEACHERS_SUCCESS,
  GET_COUNT_CURRENT,
  GET_COUNT_STUDENT,
  GET_SCHEDULES
};
