export const GET_ATTENDANCES_SUCCESS = "GET_ATTENDANCES_SUCCESS";
export const POST_ATTENDANCES_SUCCESS = 'POST_ATTENDANCES_SUCCESS'
export const POST_MANY_ATTENDANCES_SUCCESS = 'POST_MANY_ATTENDANCES_SUCCESS'
export const UPDATE_ATTENDANCES_SUCCESS = 'UPDATE_ATTENDANCES_SUCCESS'
export const UPDATE_MANY_ATTENDANCES_SUCCESS = 'UPDATE_MANY_ATTENDANCES_SUCCESS'
export const DELETE_ONE_ATTENDANCES_SUCCESS = 'DELETE_ONE_ATTENDANCES_SUCCESS'
export const DELETE_MANY_ATTENDANCES_SUCCESS = 'DELETE_MANY_ATTENDANCES_SUCCESS'


export default {
  GET_ATTENDANCES_SUCCESS,
  POST_ATTENDANCES_SUCCESS,
  POST_MANY_ATTENDANCES_SUCCESS,
  UPDATE_ATTENDANCES_SUCCESS,
  UPDATE_MANY_ATTENDANCES_SUCCESS,
  DELETE_ONE_ATTENDANCES_SUCCESS,
  DELETE_MANY_ATTENDANCES_SUCCESS
};
